name: Generate Follow-up Metrics

on:
  issues:
    opened:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Follow-up Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.user.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: user
          output_action: push
          user: ${{ github.event.issue.user.login }}
          plugins_errors_fatal: yes
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
          
      - name: Commit and push changes
        if: github.event_name == 'issues' # Only run on issue events
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
